In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/CoreyMSchafer/code_snippets/master/Python/Pandas/10-Datetime-Timeseries/ETH_1h.csv')

In [3]:
df.head()

               Date  Symbol    Open    High     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3  2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4  2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71

In [4]:
df.shape

(23674, 7)

 Know that our date column is in a string format , if we want to know what day was march 13 we will get error.
As you will see soon.

In [5]:
df.loc[0, 'Date'].day_name()

AttributeError: 'str' object has no attribute 'day_name'

In [6]:
df['Date'] = pd.to_datetime(df['Date']) # still string format.

ValueError: ('Unknown string format:', '2020-03-13 08-PM')

In [7]:
df['Date'] = pd.to_datetime(df['Date'], format = '%Y-%m-%d %I-%p' )

In [8]:
df['Date']

0       2020-03-13 20:00:00
1       2020-03-13 19:00:00
2       2020-03-13 18:00:00
3       2020-03-13 17:00:00
4       2020-03-13 16:00:00
                ...
23669   2017-07-01 15:00:00
23670   2017-07-01 14:00:00
23671   2017-07-01 13:00:00
23672   2017-07-01 12:00:00
23673   2017-07-01 11:00:00
Name: Date, Length: 23674, dtype: datetime64[ns]

In [9]:
df.loc[0, 'Date'].day_name() # Now we can run code line 6 since we convert the date column. 
                                # if we want to access all the days we will use dt.date_name.

'Friday'

In [10]:
df['Date'].dt.day_name()

0          Friday
1          Friday
2          Friday
3          Friday
4          Friday
           ...
23669    Saturday
23670    Saturday
23671    Saturday
23672    Saturday
23673    Saturday
Name: Date, Length: 23674, dtype: object

So, let's created colum for day of the week.

In [15]:
df['DayofWeek'] = df['Date'].dt.day_name()

In [16]:
df

,Date,Symbol,Open,High,Low,Close,Volume,DayofWeek
0,2020-03-13 20:00:00,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,Friday
1,2020-03-13 19:00:00,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,Friday
2,2020-03-13 18:00:00,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,Friday
3,2020-03-13 17:00:00,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,Friday
4,2020-03-13 16:00:00,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,Friday
...,...,...,...,...,...,...,...,...
23669,2017-07-01 15:00:00,ETHUSD,265.74,272.74,265.00,272.57,1500282.55,Saturday
23670,2017-07-01 14:00:00,ETHUSD,268.79,269.90,265.00,265.74,1702536.85,Saturday
23671,2017-07-01 13:00:00,ETHUSD,274.83,274.93,265.00,268.79,3010787.99,Saturday
23672,2017-07-01 12:00:00,ETHUSD,275.01,275.01,271.00,274.83,824362.87,Saturday
23673,2017-07-01 11:00:00,ETHUSD,279.98,279.99,272.10,275.01,679358.87,Saturday

In [17]:
df['Date'].min()

Timestamp('2017-07-01 11:00:00')

In [18]:
df['Date'].max()

Timestamp('2020-03-13 20:00:00')

In [20]:
df['Date'].max()-df['Date'].min() # almost thousand days

Timedelta('986 days 09:00:00')

What about if  we want to filter by date? so now that we converted date time we can do that.

In [28]:
filt = (df['Date'] >='2019') &  (df['Date'] <= '2020')

In [29]:
df.loc[filt]

,Date,Symbol,Open,High,Low,Close,Volume,DayofWeek
1748,2020-01-01 00:00:00,ETHUSD,128.54,128.54,128.12,128.34,245119.91,Wednesday
1749,2019-12-31 23:00:00,ETHUSD,128.33,128.69,128.14,128.54,440678.91,Tuesday
1750,2019-12-31 22:00:00,ETHUSD,128.38,128.69,127.95,128.33,554646.02,Tuesday
1751,2019-12-31 21:00:00,ETHUSD,127.86,128.43,127.72,128.38,350155.69,Tuesday
1752,2019-12-31 20:00:00,ETHUSD,127.84,128.34,127.71,127.86,428183.38,Tuesday
...,...,...,...,...,...,...,...,...
10504,2019-01-01 04:00:00,ETHUSD,130.75,133.96,130.74,131.96,2791135.37,Tuesday
10505,2019-01-01 03:00:00,ETHUSD,130.06,130.79,130.06,130.75,503732.63,Tuesday
10506,2019-01-01 02:00:00,ETHUSD,130.79,130.88,129.55,130.06,838183.43,Tuesday
10507,2019-01-01 01:00:00,ETHUSD,131.62,131.62,130.77,130.79,434917.99,Tuesday
10508,2019-01-01 00:00:00,ETHUSD,130.53,131.91,130.48,131.62,1067136.21,Tuesday

In [31]:
df.set_index('Date', inplace = True)      # add inplace to make the change permanent

In [32]:
df

,Symbol,Open,High,Low,Close,Volume,DayofWeek
Date,,,,,,,
2020-03-13 20:00:00,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,Friday
2020-03-13 19:00:00,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,Friday
2020-03-13 18:00:00,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,Friday
2020-03-13 17:00:00,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,Friday
2020-03-13 16:00:00,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,Friday
...,...,...,...,...,...,...,...
2017-07-01 15:00:00,ETHUSD,265.74,272.74,265.00,272.57,1500282.55,Saturday
2017-07-01 14:00:00,ETHUSD,268.79,269.90,265.00,265.74,1702536.85,Saturday
2017-07-01 13:00:00,ETHUSD,274.83,274.93,265.00,268.79,3010787.99,Saturday
2017-07-01 12:00:00,ETHUSD,275.01,275.01,271.00,274.83,824362.87,Saturday
2017-07-01 11:00:00,ETHUSD,279.98,279.99,272.10,275.01,679358.87,Saturday

In [32]:
df['2020']

                     Symbol    Open    High     Low   Close      Volume
Date
2020-03-13 20:00:00  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
2020-03-13 19:00:00  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2020-03-13 18:00:00  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
2020-03-13 17:00:00  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
2020-03-13 16:00:00  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                     ...     ...     ...     ...     ...         ...
2020-01-01 04:00:00  ETHUSD  129.57  130.00  129.50  129.56   702786.82
2020-01-01 03:00:00  ETHUSD  130.37  130.44  129.38  129.57   496704.23
2020-01-01 02:00:00  ETHUSD  130.14  130.50  129.91  130.37   396315.72
2020-01-01 01:00:00  ETHUSD  128.34  130.14  128.32  130.14   635419.40
2020-01-01 00:00:00  ETHUSD  128.54  128.54  128.12  128.34   245119.91

[1749 rows x 6 columns]

In [34]:
df['2020-01':'2020-02'] # slicing

,Symbol,Open,High,Low,Close,Volume,DayofWeek
Date,,,,,,,
2020-02-29 23:00:00,ETHUSD,223.35,223.58,216.83,217.31,1927939.88,Saturday
2020-02-29 22:00:00,ETHUSD,223.48,223.59,222.14,223.35,535998.57,Saturday
2020-02-29 21:00:00,ETHUSD,224.63,225.14,222.74,223.48,561158.03,Saturday
2020-02-29 20:00:00,ETHUSD,225.31,225.33,223.50,224.63,511648.65,Saturday
2020-02-29 19:00:00,ETHUSD,225.09,225.85,223.87,225.31,1250856.20,Saturday
...,...,...,...,...,...,...,...
2020-01-01 04:00:00,ETHUSD,129.57,130.00,129.50,129.56,702786.82,Wednesday
2020-01-01 03:00:00,ETHUSD,130.37,130.44,129.38,129.57,496704.23,Wednesday
2020-01-01 02:00:00,ETHUSD,130.14,130.50,129.91,130.37,396315.72,Wednesday
2020-01-01 01:00:00,ETHUSD,128.34,130.14,128.32,130.14,635419.40,Wednesday
2020-01-01 00:00:00,ETHUSD,128.54,128.54,128.12,128.34,245119.91,Wednesday

In [37]:
df['2020-01':'2020-02']['Close'].mean()

195.16559027777814

In [5]:
df

SyntaxError: invalid syntax (<ipython-input-5-f51d8107713e>, line 1)

In [6]:
df['Date'] = pd.to_datetime(df['Date'], format = '%Y-%m-%d %I-%p' )

In [7]:
df

                     Date  Symbol    Open    High     Low   Close      Volume
0     2020-03-13 20:00:00  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1     2020-03-13 19:00:00  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2     2020-03-13 18:00:00  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3     2020-03-13 17:00:00  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4     2020-03-13 16:00:00  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                   ...     ...     ...     ...     ...     ...         ...
23669 2017-07-01 15:00:00  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670 2017-07-01 14:00:00  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671 2017-07-01 13:00:00  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672 2017-07-01 12:00:00  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673 2017-07-01 11:00:00  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [9]:
df.set_index('Date', inplace = True)

In [10]:
df

                     Symbol    Open    High     Low   Close      Volume
Date
2020-03-13 20:00:00  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
2020-03-13 19:00:00  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2020-03-13 18:00:00  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
2020-03-13 17:00:00  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
2020-03-13 16:00:00  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                     ...     ...     ...     ...     ...         ...
2017-07-01 15:00:00  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
2017-07-01 14:00:00  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
2017-07-01 13:00:00  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
2017-07-01 12:00:00  ETHUSD  275.01  275.01  271.00  274.83   824362.87
2017-07-01 11:00:00  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 6 columns]

In [14]:
(df.loc[df['High'] >= 200])

                     Symbol    Open    High     Low   Close      Volume
Date
2020-03-11 08:00:00  ETHUSD  199.07  201.02  197.93  198.30   844669.43
2020-03-11 06:00:00  ETHUSD  199.38  200.36  198.24  198.25   419568.28
2020-03-11 05:00:00  ETHUSD  200.62  200.62  198.32  199.38   817773.68
2020-03-11 04:00:00  ETHUSD  201.84  202.22  200.62  200.62   580676.70
2020-03-11 03:00:00  ETHUSD  200.96  202.41  200.32  201.84   504032.33
...                     ...     ...     ...     ...     ...         ...
2017-07-01 15:00:00  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
2017-07-01 14:00:00  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
2017-07-01 13:00:00  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
2017-07-01 12:00:00  ETHUSD  275.01  275.01  271.00  274.83   824362.87
2017-07-01 11:00:00  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[14715 rows x 6 columns]

In [36]:
df['2017-07':'2020-03']['Close'].mean()

324.92660133479814

In [17]:
#df.loc[df.Symbol=='ETHUSD']  # both codes do the same thing filtering by colunms level.
new_df = df.loc[(df['Symbol']=='ETHUSD') & (df['High'] >=130)]

In [19]:
#new_df.to_csv('filter.csv')

In [20]:
new_df

                     Date  Symbol    Open    High     Low   Close      Volume
0     2020-03-13 20:00:00  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1     2020-03-13 19:00:00  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
6     2020-03-13 14:00:00  ETHUSD  134.03  137.90  125.50  128.39  3733916.89
7     2020-03-13 13:00:00  ETHUSD  131.35  140.95  128.99  134.03  9582732.93
8     2020-03-13 12:00:00  ETHUSD  128.93  134.60  126.95  131.35  3906590.52
...                   ...     ...     ...     ...     ...     ...         ...
23669 2017-07-01 15:00:00  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670 2017-07-01 14:00:00  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671 2017-07-01 13:00:00  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672 2017-07-01 12:00:00  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673 2017-07-01 11:00:00  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[21620 rows x 7 columns]